# -----------------------------------------------------------------------------
#
# This file is part of the xPack project (http://xpack.github.io).
# Copyright (c) 2025 Liviu Ionescu. All rights reserved.
#
# Permission to use, copy, modify, and/or distribute this software
# for any purpose is hereby granted, under the terms of the MIT license.
#
# If a copy of the license was not distributed with this file, it can
# be obtained from https://opensource.org/licenses/MIT.
#
# -----------------------------------------------------------------------------

  name: 'Test SourceForge downloads'

  on:
    schedule:
      - cron: '45 * * * 5' # every Sunday at midnight
    workflow_dispatch:

  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            repository: xpack-dev-tools/xbb-helper-xpack
            ref: 'xpack'

        - name: Show environment
          run: |
            ls -lLA
            env | sort | grep -E '^[^ \t]+='

          - name: Run test
          run: |
            #!/usr/bin/env bash
            set -e
            set -x

            # The script is in the xbb-helper-xpack repo.
            source maintenance-scripts/download-sourceforge-source.sh

            function download_sourceforge_2025_no_darwin()
            {
              local name="$1"
              local version="$2"
              local threshold=$3

              download_sourceforge_one "${name}" "${version}" "win32-x64" ${threshold}
              download_sourceforge_one "${name}" "${version}" "linux-x64" ${threshold}
              download_sourceforge_one "${name}" "${version}" "linux-arm64" ${threshold}
            }

            date

            download_sourceforge_2025_no_darwin "gcc" "14.2.0-2" 30000
            download_sourceforge_2025_no_darwin "gcc" "13.3.0-2" 30000
            download_sourceforge_2025_no_darwin "gcc" "12.4.0-2" 30000
            download_sourceforge_2025_no_darwin "gcc" "11.5.0-2" 30000

